### ISSUE TITLE
TypeError: Key must be a buffer

### ISSUE THREAD

**Issue by saasivarma** [doowb/angular-pusher#28]
Hi doowb,
Thanks for the pusher sample, i really appreciate your work. 
I'm getting an error while updating from multiple browser. i'm mentioned the error 
 
![image](https://user-images.githubusercontent.com/9442106/31052708-225ab0de-a6aa-11e7-935a-4029c4465068.png)

can you help me out. I hope for your reply

**Comment by doowb** [comment]
Those errors are coming from the `pusher` npm library. There have probably been changes since I created this example so you might have to look at that library to see if there's something different that you need to do in your `server.js` file (line 62 is where the error comes from).

Also, in the client side code, you can set the url to the `pusher.js` file that you want to use. If there were api changes between the one `angular-pusher` originally used and now, it might cause some errors.

I think `pusher` released an offical angular library that you might want to try. That is probably more up-to-date.

**Comment by saasivarma** [comment]
Yes there was an issue in pusher.js , 
I will  rewrite from scratch(need to integrate with APIs), so that i can identify the issue. I'll try that and revert back to you.

Thanks for the help Doowb.
